In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("car_evaluation.csv")

In [3]:
df

vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   vhigh    1727 non-null   object
 1   vhigh.1  1727 non-null   object
 2   2        1727 non-null   object
 3   2.1      1727 non-null   object
 4   small    1727 non-null   object
 5   low      1727 non-null   object
 6   unacc    1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [5]:
df.shape

(1727, 7)

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
df=df.apply(LabelEncoder().fit_transform)

In [8]:
df

vhigh  vhigh.1  2  2.1  small  low  unacc
0         3        3  0    0      2    2      2
1         3        3  0    0      2    0      2
2         3        3  0    0      1    1      2
3         3        3  0    0      1    2      2
4         3        3  0    0      1    0      2
...     ...      ... ..  ...    ...  ...    ...
1722      1        1  3    2      1    2      1
1723      1        1  3    2      1    0      3
1724      1        1  3    2      0    1      2
1725      1        1  3    2      0    2      1
1726      1        1  3    2      0    0      3

[1727 rows x 7 columns]

In [9]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [10]:
X

vhigh  vhigh.1  2  2.1  small  low
0         3        3  0    0      2    2
1         3        3  0    0      2    0
2         3        3  0    0      1    1
3         3        3  0    0      1    2
4         3        3  0    0      1    0
...     ...      ... ..  ...    ...  ...
1722      1        1  3    2      1    2
1723      1        1  3    2      1    0
1724      1        1  3    2      0    1
1725      1        1  3    2      0    2
1726      1        1  3    2      0    0

[1727 rows x 6 columns]

In [11]:
y

0       2
1       2
2       2
3       2
4       2
       ..
1722    1
1723    3
1724    2
1725    1
1726    3
Name: unacc, Length: 1727, dtype: int32

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [14]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
classifier=RandomForestClassifier(n_estimators=100,random_state=42)

In [16]:
classifier.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [17]:
classifier.score(X_test,y_test)

0.9624277456647399

In [28]:
y_pred=classifier.predict(X_test)
y_pred

array([2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 1, 2, 2, 1, 2, 2, 3, 0, 0, 2, 2,
       1, 0, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 3,
       2, 2, 0, 2, 3, 0, 2, 2, 2, 0, 2, 2, 2, 2, 3, 2, 2, 2, 2, 0, 2, 2,
       0, 0, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 1, 2, 2, 2, 0,
       2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 0, 3, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 2, 3, 2, 3, 0, 0, 2, 3, 0, 2, 3, 2, 0, 0,
       3, 2, 0, 2, 0, 2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 3, 2, 0, 2, 0, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 2, 3,
       3, 2, 2, 0, 3, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 3, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 1, 2, 2, 2, 1, 2, 0, 0, 0,
       2, 1, 3, 2, 1, 2, 2, 2, 0, 3, 2, 2, 2, 2, 0,

In [19]:
from sklearn.metrics import classification_report,confusion_matrix

In [20]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94        77
           1       0.91      0.67      0.77        15
           2       0.99      1.00      0.99       237
           3       0.79      0.88      0.83        17

    accuracy                           0.96       346
   macro avg       0.91      0.87      0.88       346
weighted avg       0.96      0.96      0.96       346



In [21]:
print(confusion_matrix(y_test,y_pred))

[[ 72   1   3   1]
 [  2  10   0   3]
 [  1   0 236   0]
 [  2   0   0  15]]


In [29]:
le=LabelEncoder()

In [32]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Sample input data
user_input = ['vhigh', 'low', '4', '4', 'big', 'high']

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the input list
encoded_input = label_encoder.fit_transform(user_input)

# Reshape for prediction (if needed by your model)
encoded_input = np.array(encoded_input).reshape(1, -1)

# Assuming `classifier` is your trained model
# prediction = classifier.predict(encoded_input)

print("Encoded Input:", encoded_input)
# print("Prediction:", prediction)


Encoded Input: [[4 3 0 0 1 2]]


In [34]:

prediction=classifier.predict(encoded_input)
prediction

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([2])

In [30]:
user_input=[[3,1,4,4,2,1]]
classifier.predict(user_input)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([2])